(ns safehammad.templates)

;; James Bond film titles
(def james-bond-templates ["Dr. No/NN/"
                           "From/IN/ Russia/NN/ with/IN/ Love/NN/"
                           "Gold/JJ/finger/NN/"
                           "Thunder/JJ/ball/NN/"
                           "Casino/NN/ Royale/JJ/"
                           "You/PRP/ Only/RB/ Live/VBP/ Twice/RB/"
                           "On/IN/ Her/PRP$/ Majesty/NN/'s Secret/JJ/ Service/NN/"
                           "Diamonds/NNS/ Are/VBP/ Forever/RB/"
                           "Live/VB/ and/IN/ Let/VPB/ Die/VB/"
                           "The/DT/ Man/NN/ with/IN/ the/DT/ Golden/JJ/ Gun/NN/"
                           "The/DT/ Spy/NN/ Who/WDT/ Loved/VBD/ Me/PRP/"
                           "Moon/NN/raker/NN/"
                           "For/IN/ Your/PRP$/ Eyes/NNS/ Only/RB/"
                           "Octo/JJ/pussy/NN/"
                           "Never/RB/ Say/VPB/ Never/NN/ Again/RB/"
                           "A/DT/ View/NN/ to/IN/ a/DT/ Kill/NN/"
                           "The/DT/ Living/JJ/ Daylights/NN/"
                           "Licence/NN/ to/IN/ Kill/VB/"
                           "Golden/JJ/eye/NN/"
                           "Tomorrow/NN/ Never/RB/ Dies/VBZ/"
                           "The/DT/ World/NN/ Is/VBP/ Not/RB/ Enough/JJ/"
                           "Die/VB/ Another/JJ/ Day/NN/"
                           "Quantum/NN/ of/IN/ Solace/NN/"
                           "Sky/NN/fall/VBP/"
                           "Spectre/NN/"
                           "No/DT/ Time/NN/ to/IN/ Die/VB/"])

;; Star Wars film titles
(def star-wars-templates ["A/DT/ New/JJ/ Hope/NN/"
                          "The/DT/ Empire/NN/ Strikes/VBZ/ Back/RB/"
                          "Return/NN/ of/IN/ the/DT/ Jedi/NN/"
                          "The/DT/ Phantom/JJ/ Menace/NN/"
                          "Attack/NN/ of/IN/ the/DT/ Clones/NN/"
                          "Revenge/NN/ of/IN/ the/DT/ Sith/NN/"
                          "The/DT/ Force/NN/ Awakens/VBZ/"
                          "The/DT/ Last/JJ/ Jedi/NN/"
                          "The/DT/ Rise/NN/ of/IN/ Skywalker/NN/"])

;; Harry Potter book titles
(def harry-potter-templates ["Harry Potter and the Philosopher/NN/'s Stone/NN/"
                            "Harry Potter and the Chamber/NN/ of Secrets/NN/"
                            "Harry Potter and the Prisoner/NN/ of Azkaban/NN/"
                            "Harry Potter and the Goblet/NN/ of Fire/NN/"
                            "Harry Potter and the Order/NN/ of the Phoenix/NN/"
                            "Harry Potter and the Half/JJ/-Blood/NN/ Prince/NN/"
                            "Harry Potter and the Deathly/JJ/ Hallows/NN/"
                            "The Cursed/JJ/ Child/NN/"])

;; Popular English proverbs and sayings
(def proverb-templates ["A bad/JJ/ workman/NN/ always/RB/ blames/VBZ/ his/PRP$/ tools/NNS/."
                        "A bird/NN/ in hand/NN/ is worth two in the bush/NN/."
                        "Absence/NN/ makes the heart/NN/ grow/VB/ fonder/JJR/."
                        "A cat/NN/ has/VBZ/ nine/JJ/ lives/NNS/."
                        "Actions/NNS/ speak/VB/ louder/JJR/ than words/NNS/."
                        "A leopard/NN/ can’t change/VB/ its spots/NNS/."
                        "All/NN/ that glitters/VBZ/ is not gold/NN/."
                        "A picture/NN/ is worth a thousand/JJ/ words/NNS/."
                        "A stitch/NN/ in time saves/VBZ/ nine/JJ/"
                        "Beauty/NN/ is in the eye/NN/ of the beholder/NN/."
                        "Best/JJ/ things/NNS/ in life/NN/ are free/JJ/."
                        "Blood/NN/ is thicker/JJR/ than water/NN/."
                        "Curiosity/NN/ killed/VBD/ the cat/NN/."
                        "Don’t blow/VB/ your/PRP$/ own/JJ/ trumpet/NN/."
                        "Don’t count/VB/ your/PRP$/ chickens/NNS/ before they hatch/VB/."
                        "Don’t put/VB/ all your eggs/NNS/ in one basket/NN/."
                        "The early/JJ/ bird/NN/ catches/VBZ/ the worm/NN/."
                        "Every/JJ/ cloud/NN/ has/VBZ/ a silver/JJ/ lining/NN/."
                        "Good/JJ/ things/NNS/ come/VB/ to those who wait/VB/."
                        "It’s better/JJR/ to be safe/JJ/ than sorry/JJ/."
                        "Rome/NN/ wasn’t built/VB/ in a day/NN/."
                        "The grass/NN/ is greener/JJR/ on the other side/NN/"
                        "Too many cooks/NNS/ spoil/VB/ the broth/NN/."
                        "Two wrongs/NNS/ don’t make/VB/ a right/NN/."])

;; Power Rangers Dino Charge episodes
(def power-rangers-templates ["Powers/NNS/ from/IN/ the Past/NN/"
                              "Past/NN/, Present/NN/ and Fusion/NN/"
                              "A Fool/NN/'s Hour/NN/"
                              "Return/NN/ of/IN/ the Caveman/NN/"
                              "Breaking/VB/ Black/JJ/"
                              "The Tooth/NN/ Hurts/VBZ/"
                              "Let Sleeping/VB/ Zords/NNS/ Lie/VB/"
                              "Double/JJ/ Ranger/NN/, Double/JJ/ Danger/NN/"
                              "When Logic/NN/ Fails/VBZ/"
                              "The Royal/JJ/ Rangers/NNS/"
                              "Break/VB/ Out/IN/"
                              "Knight/NN/ After/IN/ Knights/NNS/"
                              "Sync/VB/ or Swim/VB/"
                              "True/JJ/ Black/JJ/"
                              "Rise/VB/ of a Ranger/NN/"
                              "No Matter How You Slice/VB/ It/NNS/"
                              "World/NN/ Famous/JJ/! (in New/JJ/ Zealand/NN/)"
                              "Deep/JJ/ Down/JJ/ Under/JJ/"
                              "Wishing/VB/ for a Hero/NN/"
                              "One/JJ/ More/JJ/ Energem/NN/"])
